### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by Lavhe** [JMRSquared/CoPortal#16]
Create a basic User Profile page

**HINTS**

![image](https://user-images.githubusercontent.com/13318139/53370842-7470d380-3957-11e9-944c-211290027dc6.png)

![image](https://user-images.githubusercontent.com/13318139/53370921-a84bf900-3957-11e9-8840-899c92227dce.png)

We want it to be as simple as possible
> Be ready to implement it on the website as well *soon*

It must contain basic details of the student 
- [x] Full names
- [x] Username
- [x] Profile picture
- [x] ID number
- [x] Parent's details
- [x] Number of modules they are doing , and maybe list them

> IF THERE IS NO SUCH API THAT RETURNS THOSE STAFF I WILL CREATE IT, FOR NOW WORK WITH HARD CODED DATA

**Comment by Lavhe** [comment]
@netshedzo Please change the route to the profile to be something more understandable

e.g 
```
"/profile/view": {
      name: "profile",
      path: "/profile/view/:ProfileId",
      component: Profile,
      meta: {
        title: "Profile",
        authLevel: 0
     }
},
```

- [ ] I have applied the change

**Comment by netshedzo** [comment]
I thought you wanted it to be like that since the route was like that .I'll change it.. but is the UI fine?

**Comment by Lavhe** [comment]
I am on windows 😢
I dont have nativescript set up here

Please send a screenshot here

👇

**Comment by netshedzo** [comment]
![screenshot_2019-02-27-15-35-32](https://user-images.githubusercontent.com/15184759/53494072-8cef0400-3aa5-11e9-9ba8-3e2c87e8f429.png)

**Comment by Lavhe** [comment]
👍 
I like
