### ISSUE TITLE
Unable to run project due to SDK

### ISSUE THREAD

**Issue by Lavhe** [JMRSquared/CoPortal#20]
Have you tried the following?

- [x] Remove *node_modules* and *platforms* and rerun `npm install` then `tns debug android --bundle --hmr`
- [x] Check the location of your sdk , i.e `$ANDROID_HOME/tools/bin` , and see if it matches the one on Android Studio
- [x] Have you checked if the install SDK is the correct one on the error.
- [x] Tried the solutions on this link https://stackoverflow.com/questions/39760172/you-have-not-accepted-the-license-agreements-of-the-following-sdk-components

**Comment by Lavhe** [comment]
Still not fixed?

**Comment by terrenceilidio** [comment]
No man i have tried to accept all licenses but still get the same error
